version: '3.8'

services:
  api:
    build: ./api
    environment:
      DB_URL: jdbc:postgresql://sportshop-db-01.czymaq4wobwh.us-east-2.rds.amazonaws.com:5432/sportshop?sslmode=require
      DB_USER: admin_user
      DB_PASSWORD: 1232123Ct
    ports:
      - "8080:8080"
    networks:
      - sportshop_net
    restart: unless-stopped

  web:
    build: ./web
    ports:
      - "80:80"
    depends_on:
      - api
    networks:
      - sportshop_net
    restart: unless-stopped

networks:
  sportshop_net:
    driver: bridge
